### PR TITLE
Feature/141/update-initiative-card-to-fit-figma-design

### LINKED ISSUE #141: [Feature] Update Initiative Card to Fit Figma Design
The current initiative card does not 100% reflect the design on Figma, so we need to update it.

Screenshot from 2024-02-26 11-46-57
Screenshot from 2024-02-26 11-47-10

### PR DESCRIPTION
**Pull request by AmirAgassi**
🎨 [Update Initiative Card to Fit Figma Design #141](https://github.com/LaurierCS/Website/issues/141)

🔍 **What's Included**
- Updated assets for `down_arrow.svg`, `plant.svg`, and adjustments in `index.tsx` for exporting these new assets.
- Major refactoring and enhancements in `PODS.tsx` to match Figma design specifications, including UI adjustments and functionality improvements for better user experience.
- Adjustments in `ReviewSessions.tsx` that look cool (optional).
- Extensive updates to `styles.ts` to accommodate new design requirements.

📁 Files Affected:
- `src/assets/down_arrow.svg`
- `src/assets/plant.svg`
- `src/assets/index.tsx`
- `src/components/InitiativesSection/initiatives/PODS.tsx`
- `src/components/InitiativesSection/initiatives/ReviewSessions.tsx`
- `src/components/InitiativesSection/initiatives/styles.ts`

✅ **TODO**
- [ ] Make it responsive fr

### CODE REVIEW

**Comment by juancwu** [comment]
Change the base to `dev` since the component is not ready for production.

**Comment by juancwu** [comment]
@AmirAgassi can you run `pnpm lint --fix` to fix the eslint issue?

**Review by juancwu — COMMENTED** [review]
Everything looks good aside from the failing eslint check.

**Comment by AmirAgassi** [comment]
> @AmirAgassi can you run `pnpm lint --fix` to fix the eslint issue?

Whoops, didn't notice the eslint error yesterday. I gave it a quick run with `--fix` and fixed the apostrophe, all good now 💯

**Review by juancwu — APPROVED** [review]

**Pull request merged**
