### PR TITLE
Events section

### PR DESCRIPTION
**Pull request by juancwu**
Don't ask, just merge 👍

### CODE REVIEW

**Review by sshakibbb — CHANGES_REQUESTED** [review]
Styling on the Discord button and Newsletter section is wrong now.

The relative sizing of each text element in the Newsletter section before was correct, but it was originally smaller across the board when I made it. I was told to leave it like that because of some global styling settings that needed to be fixed that would enlarge the entire section uniformly. 

In your PR now though the heading is too large relative to the other elements, not sure why that happened but I don't think it's a huge deal? The subscribe button definitely is though.

Current version of main:
image
image

Your PR:
image
image

**Comment by juancwu** [comment]
I figured what is wrong. Will update this tonight after work.

**Review by aidantrabs — APPROVED** [review]

**Comment by juancwu** [comment]
I love how this PR started with don't ask anything, then bringing something up to approve to merge to revert the merge lol. What even happened here since my last comment

**Comment by aidantrabs** [comment]
> I love how this PR started with don't ask anything, then bringing something up to approve to merge to revert the merge lol. What even happened here since my last comment

Man, I did not see Keebs' review, merged and wanted then decided to revert but then I was like meh it won't hurt to leave it so I closed PR and then it got reverted again. TLDR; due diligence lacking.

**Comment by sshakibbb** [comment]
All gooood homies! If anything its just a small thing to laugh together about😝

Take your time with fixing the issues and feel free to just make another PR when you're done Juan

**Pull request merged**
